micronaut:
  application:
    name: shortener-micronaut
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/shortener
    driverClassName: org.postgresql.Driver
    username: shortener
    password: shortener
